name: windows_usb_printer
description: Windows 平台使用，提供 1. 搜索获取已安装驱动的打印机列表 2. 向指定打印机发送打印内容
version: 0.0.2+4
author: lixiaohong<liyufengisme@gmail.com>
homepage: https://github.com/liyufengrex/windows_usb_printer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  win32: ^4.1.1
  ffi: ^2.0.2

dev_dependencies:
  test: ^1.24.6


flutter:
  uses-material-design: true



